main:
  - identifier: home
    url: https://hbs.razonyang.com/
    pre: <i class="fas fa-home"></i>
    post: <span class="d-lg-none ms-1">Home</span>
    weight: 1

  - name: Support
    identifier: support
    weight: 80
  - name: Discussions
    identifier: discussions
    parent: support
    url: 'https://github.com/razonyang/hugo-theme-bootstrap/discussions/new'
    weight: 1
  - name: Bug Report
    identifier: repository
    parent: support
    url: 'https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=bug_report.md'
    weight: 2
  - name: Features Request
    identifier: feature-request
    parent: support
    url: https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=feature_request.md
    weight: 3
