main:
  - identifier: home
    name: Home
    url: https://hbs.razonyang.com/
    params:
      icon: <i class="fas fa-fw fa-home text-success"></i>
    weight: 1

  - identifier: blog
    name: Blog
    params:
      icon: <i class="fas fa-fw fa-blog text-warning"></i>
    weight: 2
  - name: Archives
    url: https://hbs.razonyang.com/v1/en/archives/
    params:
      icon: <i class="fas fa-fw fa-archive"></i>
    weight: 1
    parent: blog
  - name: Series
    url: https://hbs.razonyang.com/v1/en/series/
    params:
      icon: <i class="fas fa-fw fa-columns"></i>
    weight: 2
    parent: blog
  - name: Categories
    url: https://hbs.razonyang.com/v1/en/categories/
    params:
      icon: <i class="fas fa-fw fa-folder"></i>
    weight: 3
    parent: blog
  - name: Tags
    url: https://hbs.razonyang.com/v1/en/tags/
    params:
      icon: <i class="fas fa-fw fa-tags"></i>
    weight: 4
    parent: blog
  - name: Authors
    url: https://hbs.razonyang.com/v1/en/authors/
    params:
      icon: <i class="fas fa-fw fa-user"></i>
    weight: 5
    parent: blog

  - name: Support
    identifier: support
    params:
      icon: <i class="fas fa-fw fa-info-circle text-info"></i>
      description: The HBS Support Community.
    weight: 80
  - name: Repository
    identifier: repository
    parent: support
    url: "https://github.com/razonyang/hugo-theme-bootstrap/"
    params:
      icon: <i class="fab fa-fw fa-github text-primary"></i>
    weight: 1
  - name: Discussions
    identifier: discussions
    parent: support
    url: "https://github.com/razonyang/hugo-theme-bootstrap/discussions/new"
    params:
      icon: <i class="fas fa-fw fa-comments text-success"></i>
      description: Ask and discuss questions with others.
    weight: 2
  - name: Bug Report
    identifier: bug-report
    parent: support
    url: "https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=bug_report.yml"
    params:
      icon: <i class="fas fa-fw fa-bug text-danger"></i>
      description: Suggest new or updated features.
    weight: 3
  - name: Features Request
    identifier: feature-request
    parent: support
    url: https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=feature_request.yml
    params:
      icon: <i class="fas fa-fw fa-lightbulb text-warning"></i>
      description: Tell us about a bug or issue.
    weight: 4
  - identifier: support-divider
    parent: support
    params:
      divider: true
    weight: 5
  - name: Get Involved
    identifier: get-involved
    parent: support
    url: https://hbs.razonyang.com/v1/en/docs/get-involved/
    params:
      icon: <i class="fas fa-fw fa-handshake"></i>
    weight: 6
  - name: FAQ
    identifier: faq
    parent: support
    url: https://hbs.razonyang.com/v1/en/faq/
    params:
      icon: <i class="fas fa-fw fa-info-circle text-info"></i>
    weight: 7
