brand: HBS
description: Fast, responsive, multipurpose and feature-rich Hugo theme. It is used for blog and document sites typically.

palette: purple
searchBar: false

topAppBar:
  social:
    github: razonyang/hugo-theme-bootstrap
