brand: HBS
description: Fast, responsive, multipurpose, open source (MIT license) and feature-rich Hugo theme. It is used for blog and document sites typically.
mainSections:
  - blog

palette: purple

post:
  copyright: false
  featuredImage: true

pwa:
  manifest:
    short_name: HBS

topAppBar:
  social:
    github: razonyang/hugo-theme-bootstrap
    patreon: razonyang
    paypal: razonyang

docsearch:
  appId: QJSHIZ7V63
  apiKey: 664dc009c2ff1891823c07720e5f79ed
  indexName: razonyang_hbs

utterances:
  repo: razonyang/hugo-theme-bootstrap-site
