brand: HBS
description: Fast, responsive, multipurpose and feature-rich Hugo theme. It is used for blog and document sites typically.

palette: purple

pwa:
  manifest:
    short_name: HBS

topAppBar:
  social:
    github: razonyang/hugo-theme-bootstrap

docsearch:
  appId: QJSHIZ7V63
  apiKey: ddd1e0eb4b5bc657e3a1acbcb55fa06a
  indexName: hbs_all
